on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Perform the tests
    steps:
      - uses: actions/checkout@v3
      - name: Install modules
        run: npm install
      - name: Run tests
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: npm run vibecheck
